// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package eth_framing_reg_pkg;

  // Address widths within the block
  parameter int BlockAw = 4;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {
    logic [31:0] q;
  } eth_framing_reg2hw_config0_reg_t;

  typedef struct packed {
    struct packed {
      logic [15:0] q;
    } upper_mac_address;
    struct packed {
      logic        q;
    } promiscuous;
    struct packed {
      logic        q;
    } phy_mdclk;
    struct packed {
      logic        q;
    } phy_mdio_o;
    struct packed {
      logic        q;
    } phy_mdio_oe;
  } eth_framing_reg2hw_config1_reg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } eth_framing_hw2reg_config2_reg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } eth_framing_hw2reg_config3_reg_t;

  // Register -> HW type
  typedef struct packed {
    eth_framing_reg2hw_config0_reg_t config0; // [51:20]
    eth_framing_reg2hw_config1_reg_t config1; // [19:0]
  } eth_framing_reg2hw_t;

  // HW -> register type
  typedef struct packed {
    eth_framing_hw2reg_config2_reg_t config2; // [65:33]
    eth_framing_hw2reg_config3_reg_t config3; // [32:0]
  } eth_framing_hw2reg_t;

  // Register offsets
  parameter logic [BlockAw-1:0] ETH_FRAMING_CONFIG0_OFFSET = 4'h 0;
  parameter logic [BlockAw-1:0] ETH_FRAMING_CONFIG1_OFFSET = 4'h 4;
  parameter logic [BlockAw-1:0] ETH_FRAMING_CONFIG2_OFFSET = 4'h 8;
  parameter logic [BlockAw-1:0] ETH_FRAMING_CONFIG3_OFFSET = 4'h c;

  // Register index
  typedef enum int {
    ETH_FRAMING_CONFIG0,                                                                                                              
    ETH_FRAMING_CONFIG1,
    ETH_FRAMING_CONFIG2,
    ETH_FRAMING_CONFIG3
  } eth_framing_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] ETH_FRAMING_PERMIT [4] = '{
    4'b 1111, // index[0] ETH_FRAMING_CONFIG0
    4'b 0111, // index[1] ETH_FRAMING_CONFIG1
    4'b 1111, // index[2] ETH_FRAMING_CONFIG2
    4'b 1111  // index[3] ETH_FRAMING_CONFIG3
  };

endpackage

