// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Top module auto-generated by `reggen`


`include "common_cells/assertions.svh"

module eth_framing_reg_top #(
  parameter type reg_req_t = logic,
  parameter type reg_rsp_t = logic,
  parameter int AW = 4
) (
  input logic clk_i,
  input logic rst_ni,
  input  reg_req_t reg_req_i,
  output reg_rsp_t reg_rsp_o,
  // To HW
  output eth_framing_reg_pkg::eth_framing_reg2hw_t reg2hw, // Write
  input  eth_framing_reg_pkg::eth_framing_hw2reg_t hw2reg, // Read


  // Config
  input devmode_i // If 1, explicit error return for unmapped register access
);

  import eth_framing_reg_pkg::* ;

  localparam int DW = 32;
  localparam int DBW = DW/8;                    // Byte Width

  // register signals
  logic           reg_we;
  logic           reg_re;
  logic [BlockAw-1:0]  reg_addr;
  logic [DW-1:0]  reg_wdata;
  logic [DBW-1:0] reg_be;
  logic [DW-1:0]  reg_rdata;
  logic           reg_error;

  logic          addrmiss, wr_err;

  logic [DW-1:0] reg_rdata_next;

  // Below register interface can be changed
  reg_req_t  reg_intf_req;
  reg_rsp_t  reg_intf_rsp;


  assign reg_intf_req = reg_req_i;
  assign reg_rsp_o = reg_intf_rsp;


  assign reg_we = reg_intf_req.valid & reg_intf_req.write;
  assign reg_re = reg_intf_req.valid & ~reg_intf_req.write;
  assign reg_addr = reg_intf_req.addr[BlockAw-1:0];
  assign reg_wdata = reg_intf_req.wdata;
  assign reg_be = reg_intf_req.wstrb;
  assign reg_intf_rsp.rdata = reg_rdata;
  assign reg_intf_rsp.error = reg_error;
  assign reg_intf_rsp.ready = 1'b1;

  assign reg_rdata = reg_rdata_next ;
  assign reg_error = (devmode_i & addrmiss) | wr_err;


  // Define SW related signals
  // Format: <reg>_<field>_{wd|we|qs}
  //        or <reg>_{wd|we|qs} if field == 1 or 0
  logic [31:0] config0_qs;
  logic [31:0] config0_wd;
  logic config0_we;
  logic [15:0] config1_upper_mac_address_qs;
  logic [15:0] config1_upper_mac_address_wd;
  logic config1_upper_mac_address_we;
  logic config1_promiscuous_qs;
  logic config1_promiscuous_wd;
  logic config1_promiscuous_we;
  logic config1_phy_mdclk_qs;
  logic config1_phy_mdclk_wd;
  logic config1_phy_mdclk_we;
  logic config1_phy_mdio_o_qs;
  logic config1_phy_mdio_o_wd;
  logic config1_phy_mdio_o_we;
  logic config1_phy_mdio_oe_qs;
  logic config1_phy_mdio_oe_wd;
  logic config1_phy_mdio_oe_we;
  logic [31:0] config2_qs;
  logic [31:0] config3_qs;

  // Register instances
  // R[config0]: V(False)

  prim_subreg #(
    .DW      (32),
    .SWACCESS("RW"),
    .RESVAL  (32'h890702)
  ) u_config0 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (config0_we),
    .wd     (config0_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.config0.q ),

    // to register interface (read)
    .qs     (config0_qs)
  );


  // R[config1]: V(False)

  //   F[upper_mac_address]: 15:0
  prim_subreg #(
    .DW      (16),
    .SWACCESS("RW"),
    .RESVAL  (16'h2301)
  ) u_config1_upper_mac_address (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (config1_upper_mac_address_we),
    .wd     (config1_upper_mac_address_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.config1.upper_mac_address.q ),

    // to register interface (read)
    .qs     (config1_upper_mac_address_qs)
  );


  //   F[promiscuous]: 16:16
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_config1_promiscuous (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (config1_promiscuous_we),
    .wd     (config1_promiscuous_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.config1.promiscuous.q ),

    // to register interface (read)
    .qs     (config1_promiscuous_qs)
  );


  //   F[phy_mdclk]: 17:17
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_config1_phy_mdclk (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (config1_phy_mdclk_we),
    .wd     (config1_phy_mdclk_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.config1.phy_mdclk.q ),

    // to register interface (read)
    .qs     (config1_phy_mdclk_qs)
  );


  //   F[phy_mdio_o]: 18:18
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_config1_phy_mdio_o (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (config1_phy_mdio_o_we),
    .wd     (config1_phy_mdio_o_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.config1.phy_mdio_o.q ),

    // to register interface (read)
    .qs     (config1_phy_mdio_o_qs)
  );


  //   F[phy_mdio_oe]: 19:19
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_config1_phy_mdio_oe (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (config1_phy_mdio_oe_we),
    .wd     (config1_phy_mdio_oe_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.config1.phy_mdio_oe.q ),

    // to register interface (read)
    .qs     (config1_phy_mdio_oe_qs)
  );


  // R[config2]: V(False)

  prim_subreg #(
    .DW      (32),
    .SWACCESS("RO"),
    .RESVAL  (32'h0)
  ) u_config2 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    .we     (1'b0),
    .wd     ('0  ),

    // from internal hardware
    .de     (hw2reg.config2.de),
    .d      (hw2reg.config2.d ),

    // to internal hardware
    .qe     (),
    .q      (),

    // to register interface (read)
    .qs     (config2_qs)
  );


  // R[config3]: V(False)

  prim_subreg #(
    .DW      (32),
    .SWACCESS("RO"),
    .RESVAL  (32'h0)
  ) u_config3 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    .we     (1'b0),
    .wd     ('0  ),

    // from internal hardware
    .de     (hw2reg.config3.de),
    .d      (hw2reg.config3.d ),

    // to internal hardware
    .qe     (),
    .q      (),

    // to register interface (read)
    .qs     (config3_qs)
  );




  logic [3:0] addr_hit;
  always_comb begin
    addr_hit = '0;
    addr_hit[0] = (reg_addr == ETH_FRAMING_CONFIG0_OFFSET);
    addr_hit[1] = (reg_addr == ETH_FRAMING_CONFIG1_OFFSET);
    addr_hit[2] = (reg_addr == ETH_FRAMING_CONFIG2_OFFSET);
    addr_hit[3] = (reg_addr == ETH_FRAMING_CONFIG3_OFFSET);
  end

  assign addrmiss = (reg_re || reg_we) ? ~|addr_hit : 1'b0 ;

  // Check sub-word write is permitted
  always_comb begin
    wr_err = (reg_we &
              ((addr_hit[0] & (|(ETH_FRAMING_PERMIT[0] & ~reg_be))) |
               (addr_hit[1] & (|(ETH_FRAMING_PERMIT[1] & ~reg_be))) |
               (addr_hit[2] & (|(ETH_FRAMING_PERMIT[2] & ~reg_be))) |
               (addr_hit[3] & (|(ETH_FRAMING_PERMIT[3] & ~reg_be)))));
  end

  assign config0_we = addr_hit[0] & reg_we & !reg_error;
  assign config0_wd = reg_wdata[31:0];

  assign config1_upper_mac_address_we = addr_hit[1] & reg_we & !reg_error;
  assign config1_upper_mac_address_wd = reg_wdata[15:0];

  assign config1_promiscuous_we = addr_hit[1] & reg_we & !reg_error;
  assign config1_promiscuous_wd = reg_wdata[16];

  assign config1_phy_mdclk_we = addr_hit[1] & reg_we & !reg_error;
  assign config1_phy_mdclk_wd = reg_wdata[17];

  assign config1_phy_mdio_o_we = addr_hit[1] & reg_we & !reg_error;
  assign config1_phy_mdio_o_wd = reg_wdata[18];

  assign config1_phy_mdio_oe_we = addr_hit[1] & reg_we & !reg_error;
  assign config1_phy_mdio_oe_wd = reg_wdata[19];

  // Read data return
  always_comb begin
    reg_rdata_next = '0;
    unique case (1'b1)
      addr_hit[0]: begin
        reg_rdata_next[31:0] = config0_qs;
      end

      addr_hit[1]: begin
        reg_rdata_next[15:0] = config1_upper_mac_address_qs;
        reg_rdata_next[16] = config1_promiscuous_qs;
        reg_rdata_next[17] = config1_phy_mdclk_qs;
        reg_rdata_next[18] = config1_phy_mdio_o_qs;
        reg_rdata_next[19] = config1_phy_mdio_oe_qs;
      end

      addr_hit[2]: begin
        reg_rdata_next[31:0] = config2_qs;
      end

      addr_hit[3]: begin
        reg_rdata_next[31:0] = config3_qs;
      end

      default: begin
        reg_rdata_next = '1;
      end
    endcase
  end

  // Unused signal tieoff

  // wdata / byte enable are not always fully used
  // add a blanket unused statement to handle lint waivers
  logic unused_wdata;
  logic unused_be;
  assign unused_wdata = ^reg_wdata;
  assign unused_be = ^reg_be;

  // Assertions for Register Interface
  `ASSERT(en2addrHit, (reg_we || reg_re) |-> $onehot0(addr_hit))

endmodule

module eth_framing_reg_top_intf
#(
  parameter int AW = 4,
  localparam int DW = 32
) (
  input logic clk_i,
  input logic rst_ni,
  REG_BUS.in  regbus_slave,
  // To HW
  output eth_framing_reg_pkg::eth_framing_reg2hw_t reg2hw, // Write
  input  eth_framing_reg_pkg::eth_framing_hw2reg_t hw2reg, // Read
  // Config
  input devmode_i // If 1, explicit error return for unmapped register access
);
 localparam int unsigned STRB_WIDTH = DW/8;

`include "register_interface/typedef.svh"
`include "register_interface/assign.svh"

  // Define structs for reg_bus
  typedef logic [AW-1:0] addr_t;
  typedef logic [DW-1:0] data_t;
  typedef logic [STRB_WIDTH-1:0] strb_t;
  `REG_BUS_TYPEDEF_ALL(reg_bus, addr_t, data_t, strb_t)

  reg_bus_req_t s_reg_req;
  reg_bus_rsp_t s_reg_rsp;
  
  // Assign SV interface to structs
  `REG_BUS_ASSIGN_TO_REQ(s_reg_req, regbus_slave)
  `REG_BUS_ASSIGN_FROM_RSP(regbus_slave, s_reg_rsp)

  

  eth_framing_reg_top #(
    .reg_req_t(reg_bus_req_t),
    .reg_rsp_t(reg_bus_rsp_t),
    .AW(AW)
  ) i_regs (
    .clk_i,
    .rst_ni,
    .reg_req_i(s_reg_req),
    .reg_rsp_o(s_reg_rsp),
    .reg2hw, // Write
    .hw2reg, // Read
    .devmode_i
  );
  
endmodule


