// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Top module auto-generated by `reggen`


`include "common_cells/assertions.svh"

module eth_idma_reg_top #(
  parameter type reg_req_t = logic,
  parameter type reg_rsp_t = logic,
  parameter int AW = 8
) (
  input logic clk_i,
  input logic rst_ni,
  input  reg_req_t reg_req_i,
  output reg_rsp_t reg_rsp_o,
  // To HW
  output eth_idma_reg_pkg::eth_idma_reg2hw_t reg2hw, // Write
  input  eth_idma_reg_pkg::eth_idma_hw2reg_t hw2reg, // Read


  // Config
  input devmode_i // If 1, explicit error return for unmapped register access
);

  import eth_idma_reg_pkg::* ;

  localparam int DW = 64;
  localparam int DBW = DW/8;                    // Byte Width

  // register signals
  logic           reg_we;
  logic           reg_re;
  logic [BlockAw-1:0]  reg_addr;
  logic [DW-1:0]  reg_wdata;
  logic [DBW-1:0] reg_be;
  logic [DW-1:0]  reg_rdata;
  logic           reg_error;

  logic          addrmiss, wr_err;

  logic [DW-1:0] reg_rdata_next;

  // Below register interface can be changed
  reg_req_t  reg_intf_req;
  reg_rsp_t  reg_intf_rsp;


  assign reg_intf_req = reg_req_i;
  assign reg_rsp_o = reg_intf_rsp;


  assign reg_we = reg_intf_req.valid & reg_intf_req.write;
  assign reg_re = reg_intf_req.valid & ~reg_intf_req.write;
  assign reg_addr = reg_intf_req.addr[BlockAw-1:0];
  assign reg_wdata = reg_intf_req.wdata;
  assign reg_be = reg_intf_req.wstrb;
  assign reg_intf_rsp.rdata = reg_rdata;
  assign reg_intf_rsp.error = reg_error;
  assign reg_intf_rsp.ready = 1'b1;

  assign reg_rdata = reg_rdata_next ;
  assign reg_error = (devmode_i & addrmiss) | wr_err;


  // Define SW related signals
  // Format: <reg>_<field>_{wd|we|qs}
  //        or <reg>_{wd|we|qs} if field == 1 or 0
  logic [31:0] maclo_addr_qs;
  logic [31:0] maclo_addr_wd;
  logic maclo_addr_we;
  logic [15:0] machi_mdio_upper_mac_address_qs;
  logic [15:0] machi_mdio_upper_mac_address_wd;
  logic machi_mdio_upper_mac_address_we;
  logic machi_mdio_promiscuous_qs;
  logic machi_mdio_promiscuous_wd;
  logic machi_mdio_promiscuous_we;
  logic machi_mdio_phy_mdclk_qs;
  logic machi_mdio_phy_mdclk_wd;
  logic machi_mdio_phy_mdclk_we;
  logic machi_mdio_phy_mdio_o_qs;
  logic machi_mdio_phy_mdio_o_wd;
  logic machi_mdio_phy_mdio_o_we;
  logic machi_mdio_phy_mdio_oe_qs;
  logic machi_mdio_phy_mdio_oe_wd;
  logic machi_mdio_phy_mdio_oe_we;
  logic [31:0] tx_fcs_qs;
  logic [31:0] rx_fcs_qs;
  logic [31:0] src_addr_qs;
  logic [31:0] src_addr_wd;
  logic src_addr_we;
  logic [31:0] dst_addr_qs;
  logic [31:0] dst_addr_wd;
  logic dst_addr_we;
  logic [31:0] length_qs;
  logic [31:0] length_wd;
  logic length_we;
  logic [2:0] src_protocol_qs;
  logic [2:0] src_protocol_wd;
  logic src_protocol_we;
  logic [2:0] dst_protocol_qs;
  logic [2:0] dst_protocol_wd;
  logic dst_protocol_we;
  logic axi_id_qs;
  logic axi_id_wd;
  logic axi_id_we;
  logic [1:0] opt_src_burst_qs;
  logic [1:0] opt_src_burst_wd;
  logic opt_src_burst_we;
  logic [3:0] opt_src_cache_qs;
  logic [3:0] opt_src_cache_wd;
  logic opt_src_cache_we;
  logic opt_src_lock_qs;
  logic opt_src_lock_wd;
  logic opt_src_lock_we;
  logic [2:0] opt_src_prot_qs;
  logic [2:0] opt_src_prot_wd;
  logic opt_src_prot_we;
  logic [3:0] opt_src_qos_qs;
  logic [3:0] opt_src_qos_wd;
  logic opt_src_qos_we;
  logic [3:0] opt_src_region_qs;
  logic [3:0] opt_src_region_wd;
  logic opt_src_region_we;
  logic [1:0] opt_dst_burst_qs;
  logic [1:0] opt_dst_burst_wd;
  logic opt_dst_burst_we;
  logic [3:0] opt_dst_cache_qs;
  logic [3:0] opt_dst_cache_wd;
  logic opt_dst_cache_we;
  logic opt_dst_lock_qs;
  logic opt_dst_lock_wd;
  logic opt_dst_lock_we;
  logic [2:0] opt_dst_prot_qs;
  logic [2:0] opt_dst_prot_wd;
  logic opt_dst_prot_we;
  logic [3:0] opt_dst_qos_qs;
  logic [3:0] opt_dst_qos_wd;
  logic opt_dst_qos_we;
  logic [3:0] opt_dst_region_qs;
  logic [3:0] opt_dst_region_wd;
  logic opt_dst_region_we;
  logic beo_decouple_aw_qs;
  logic beo_decouple_aw_wd;
  logic beo_decouple_aw_we;
  logic beo_decouple_rw_qs;
  logic beo_decouple_rw_wd;
  logic beo_decouple_rw_we;
  logic [2:0] beo_src_max_llen_qs;
  logic [2:0] beo_src_max_llen_wd;
  logic beo_src_max_llen_we;
  logic [2:0] beo_dst_max_llen_qs;
  logic [2:0] beo_dst_max_llen_wd;
  logic beo_dst_max_llen_we;
  logic beo_src_reduce_len_qs;
  logic beo_src_reduce_len_wd;
  logic beo_src_reduce_len_we;
  logic beo_dst_reduce_len_qs;
  logic beo_dst_reduce_len_wd;
  logic beo_dst_reduce_len_we;
  logic last_qs;
  logic last_wd;
  logic last_we;
  logic req_valid_qs;
  logic req_valid_wd;
  logic req_valid_we;
  logic req_ready_qs;
  logic rsp_ready_qs;
  logic rsp_ready_wd;
  logic rsp_ready_we;
  logic rsp_valid_qs;

  // Register instances
  // R[maclo_addr]: V(False)

  prim_subreg #(
    .DW      (32),
    .SWACCESS("RW"),
    .RESVAL  (32'h890702)
  ) u_maclo_addr (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (maclo_addr_we),
    .wd     (maclo_addr_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.maclo_addr.q ),

    // to register interface (read)
    .qs     (maclo_addr_qs)
  );


  // R[machi_mdio]: V(False)

  //   F[upper_mac_address]: 15:0
  prim_subreg #(
    .DW      (16),
    .SWACCESS("RW"),
    .RESVAL  (16'h2301)
  ) u_machi_mdio_upper_mac_address (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (machi_mdio_upper_mac_address_we),
    .wd     (machi_mdio_upper_mac_address_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.machi_mdio.upper_mac_address.q ),

    // to register interface (read)
    .qs     (machi_mdio_upper_mac_address_qs)
  );


  //   F[promiscuous]: 16:16
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_machi_mdio_promiscuous (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (machi_mdio_promiscuous_we),
    .wd     (machi_mdio_promiscuous_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.machi_mdio.promiscuous.q ),

    // to register interface (read)
    .qs     (machi_mdio_promiscuous_qs)
  );


  //   F[phy_mdclk]: 17:17
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_machi_mdio_phy_mdclk (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (machi_mdio_phy_mdclk_we),
    .wd     (machi_mdio_phy_mdclk_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.machi_mdio.phy_mdclk.q ),

    // to register interface (read)
    .qs     (machi_mdio_phy_mdclk_qs)
  );


  //   F[phy_mdio_o]: 18:18
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_machi_mdio_phy_mdio_o (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (machi_mdio_phy_mdio_o_we),
    .wd     (machi_mdio_phy_mdio_o_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.machi_mdio.phy_mdio_o.q ),

    // to register interface (read)
    .qs     (machi_mdio_phy_mdio_o_qs)
  );


  //   F[phy_mdio_oe]: 19:19
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_machi_mdio_phy_mdio_oe (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (machi_mdio_phy_mdio_oe_we),
    .wd     (machi_mdio_phy_mdio_oe_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.machi_mdio.phy_mdio_oe.q ),

    // to register interface (read)
    .qs     (machi_mdio_phy_mdio_oe_qs)
  );


  // R[tx_fcs]: V(False)

  prim_subreg #(
    .DW      (32),
    .SWACCESS("RO"),
    .RESVAL  (32'h0)
  ) u_tx_fcs (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    .we     (1'b0),
    .wd     ('0  ),

    // from internal hardware
    .de     (hw2reg.tx_fcs.de),
    .d      (hw2reg.tx_fcs.d ),

    // to internal hardware
    .qe     (),
    .q      (),

    // to register interface (read)
    .qs     (tx_fcs_qs)
  );


  // R[rx_fcs]: V(False)

  prim_subreg #(
    .DW      (32),
    .SWACCESS("RO"),
    .RESVAL  (32'h0)
  ) u_rx_fcs (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    .we     (1'b0),
    .wd     ('0  ),

    // from internal hardware
    .de     (hw2reg.rx_fcs.de),
    .d      (hw2reg.rx_fcs.d ),

    // to internal hardware
    .qe     (),
    .q      (),

    // to register interface (read)
    .qs     (rx_fcs_qs)
  );


  // R[src_addr]: V(False)

  prim_subreg #(
    .DW      (32),
    .SWACCESS("RW"),
    .RESVAL  (32'h0)
  ) u_src_addr (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (src_addr_we),
    .wd     (src_addr_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.src_addr.q ),

    // to register interface (read)
    .qs     (src_addr_qs)
  );


  // R[dst_addr]: V(False)

  prim_subreg #(
    .DW      (32),
    .SWACCESS("RW"),
    .RESVAL  (32'h0)
  ) u_dst_addr (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (dst_addr_we),
    .wd     (dst_addr_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.dst_addr.q ),

    // to register interface (read)
    .qs     (dst_addr_qs)
  );


  // R[length]: V(False)

  prim_subreg #(
    .DW      (32),
    .SWACCESS("RW"),
    .RESVAL  (32'h0)
  ) u_length (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (length_we),
    .wd     (length_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.length.q ),

    // to register interface (read)
    .qs     (length_qs)
  );


  // R[src_protocol]: V(False)

  prim_subreg #(
    .DW      (3),
    .SWACCESS("RW"),
    .RESVAL  (3'h0)
  ) u_src_protocol (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (src_protocol_we),
    .wd     (src_protocol_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.src_protocol.q ),

    // to register interface (read)
    .qs     (src_protocol_qs)
  );


  // R[dst_protocol]: V(False)

  prim_subreg #(
    .DW      (3),
    .SWACCESS("RW"),
    .RESVAL  (3'h0)
  ) u_dst_protocol (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (dst_protocol_we),
    .wd     (dst_protocol_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.dst_protocol.q ),

    // to register interface (read)
    .qs     (dst_protocol_qs)
  );


  // R[axi_id]: V(False)

  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_axi_id (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (axi_id_we),
    .wd     (axi_id_wd),

    // from internal hardware
    .de     (hw2reg.axi_id.de),
    .d      (hw2reg.axi_id.d ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.axi_id.q ),

    // to register interface (read)
    .qs     (axi_id_qs)
  );


  // R[opt_src]: V(False)

  //   F[burst]: 1:0
  prim_subreg #(
    .DW      (2),
    .SWACCESS("RW"),
    .RESVAL  (2'h1)
  ) u_opt_src_burst (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (opt_src_burst_we),
    .wd     (opt_src_burst_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.opt_src.burst.q ),

    // to register interface (read)
    .qs     (opt_src_burst_qs)
  );


  //   F[cache]: 5:2
  prim_subreg #(
    .DW      (4),
    .SWACCESS("RW"),
    .RESVAL  (4'h0)
  ) u_opt_src_cache (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (opt_src_cache_we),
    .wd     (opt_src_cache_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.opt_src.cache.q ),

    // to register interface (read)
    .qs     (opt_src_cache_qs)
  );


  //   F[lock]: 6:6
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_opt_src_lock (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (opt_src_lock_we),
    .wd     (opt_src_lock_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.opt_src.lock.q ),

    // to register interface (read)
    .qs     (opt_src_lock_qs)
  );


  //   F[prot]: 9:7
  prim_subreg #(
    .DW      (3),
    .SWACCESS("RW"),
    .RESVAL  (3'h0)
  ) u_opt_src_prot (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (opt_src_prot_we),
    .wd     (opt_src_prot_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.opt_src.prot.q ),

    // to register interface (read)
    .qs     (opt_src_prot_qs)
  );


  //   F[qos]: 13:10
  prim_subreg #(
    .DW      (4),
    .SWACCESS("RW"),
    .RESVAL  (4'h0)
  ) u_opt_src_qos (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (opt_src_qos_we),
    .wd     (opt_src_qos_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.opt_src.qos.q ),

    // to register interface (read)
    .qs     (opt_src_qos_qs)
  );


  //   F[region]: 17:14
  prim_subreg #(
    .DW      (4),
    .SWACCESS("RW"),
    .RESVAL  (4'h0)
  ) u_opt_src_region (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (opt_src_region_we),
    .wd     (opt_src_region_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.opt_src.region.q ),

    // to register interface (read)
    .qs     (opt_src_region_qs)
  );


  // R[opt_dst]: V(False)

  //   F[burst]: 1:0
  prim_subreg #(
    .DW      (2),
    .SWACCESS("RW"),
    .RESVAL  (2'h1)
  ) u_opt_dst_burst (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (opt_dst_burst_we),
    .wd     (opt_dst_burst_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.opt_dst.burst.q ),

    // to register interface (read)
    .qs     (opt_dst_burst_qs)
  );


  //   F[cache]: 5:2
  prim_subreg #(
    .DW      (4),
    .SWACCESS("RW"),
    .RESVAL  (4'h0)
  ) u_opt_dst_cache (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (opt_dst_cache_we),
    .wd     (opt_dst_cache_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.opt_dst.cache.q ),

    // to register interface (read)
    .qs     (opt_dst_cache_qs)
  );


  //   F[lock]: 6:6
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_opt_dst_lock (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (opt_dst_lock_we),
    .wd     (opt_dst_lock_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.opt_dst.lock.q ),

    // to register interface (read)
    .qs     (opt_dst_lock_qs)
  );


  //   F[prot]: 9:7
  prim_subreg #(
    .DW      (3),
    .SWACCESS("RW"),
    .RESVAL  (3'h0)
  ) u_opt_dst_prot (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (opt_dst_prot_we),
    .wd     (opt_dst_prot_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.opt_dst.prot.q ),

    // to register interface (read)
    .qs     (opt_dst_prot_qs)
  );


  //   F[qos]: 13:10
  prim_subreg #(
    .DW      (4),
    .SWACCESS("RW"),
    .RESVAL  (4'h0)
  ) u_opt_dst_qos (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (opt_dst_qos_we),
    .wd     (opt_dst_qos_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.opt_dst.qos.q ),

    // to register interface (read)
    .qs     (opt_dst_qos_qs)
  );


  //   F[region]: 17:14
  prim_subreg #(
    .DW      (4),
    .SWACCESS("RW"),
    .RESVAL  (4'h0)
  ) u_opt_dst_region (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (opt_dst_region_we),
    .wd     (opt_dst_region_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.opt_dst.region.q ),

    // to register interface (read)
    .qs     (opt_dst_region_qs)
  );


  // R[beo]: V(False)

  //   F[decouple_aw]: 0:0
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_beo_decouple_aw (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (beo_decouple_aw_we),
    .wd     (beo_decouple_aw_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.beo.decouple_aw.q ),

    // to register interface (read)
    .qs     (beo_decouple_aw_qs)
  );


  //   F[decouple_rw]: 1:1
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_beo_decouple_rw (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (beo_decouple_rw_we),
    .wd     (beo_decouple_rw_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.beo.decouple_rw.q ),

    // to register interface (read)
    .qs     (beo_decouple_rw_qs)
  );


  //   F[src_max_llen]: 4:2
  prim_subreg #(
    .DW      (3),
    .SWACCESS("RW"),
    .RESVAL  (3'h0)
  ) u_beo_src_max_llen (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (beo_src_max_llen_we),
    .wd     (beo_src_max_llen_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.beo.src_max_llen.q ),

    // to register interface (read)
    .qs     (beo_src_max_llen_qs)
  );


  //   F[dst_max_llen]: 7:5
  prim_subreg #(
    .DW      (3),
    .SWACCESS("RW"),
    .RESVAL  (3'h0)
  ) u_beo_dst_max_llen (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (beo_dst_max_llen_we),
    .wd     (beo_dst_max_llen_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.beo.dst_max_llen.q ),

    // to register interface (read)
    .qs     (beo_dst_max_llen_qs)
  );


  //   F[src_reduce_len]: 8:8
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_beo_src_reduce_len (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (beo_src_reduce_len_we),
    .wd     (beo_src_reduce_len_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.beo.src_reduce_len.q ),

    // to register interface (read)
    .qs     (beo_src_reduce_len_qs)
  );


  //   F[dst_reduce_len]: 9:9
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_beo_dst_reduce_len (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (beo_dst_reduce_len_we),
    .wd     (beo_dst_reduce_len_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.beo.dst_reduce_len.q ),

    // to register interface (read)
    .qs     (beo_dst_reduce_len_qs)
  );


  // R[last]: V(False)

  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_last (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (last_we),
    .wd     (last_wd),

    // from internal hardware
    .de     (hw2reg.last.de),
    .d      (hw2reg.last.d ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.last.q ),

    // to register interface (read)
    .qs     (last_qs)
  );


  // R[req_valid]: V(False)

  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_req_valid (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (req_valid_we),
    .wd     (req_valid_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.req_valid.q ),

    // to register interface (read)
    .qs     (req_valid_qs)
  );


  // R[req_ready]: V(False)

  prim_subreg #(
    .DW      (1),
    .SWACCESS("RO"),
    .RESVAL  (1'h0)
  ) u_req_ready (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    .we     (1'b0),
    .wd     ('0  ),

    // from internal hardware
    .de     (hw2reg.req_ready.de),
    .d      (hw2reg.req_ready.d ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.req_ready.q ),

    // to register interface (read)
    .qs     (req_ready_qs)
  );


  // R[rsp_ready]: V(False)

  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_rsp_ready (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (rsp_ready_we),
    .wd     (rsp_ready_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.rsp_ready.q ),

    // to register interface (read)
    .qs     (rsp_ready_qs)
  );


  // R[rsp_valid]: V(False)

  prim_subreg #(
    .DW      (1),
    .SWACCESS("RO"),
    .RESVAL  (1'h0)
  ) u_rsp_valid (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    .we     (1'b0),
    .wd     ('0  ),

    // from internal hardware
    .de     (hw2reg.rsp_valid.de),
    .d      (hw2reg.rsp_valid.d ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.rsp_valid.q ),

    // to register interface (read)
    .qs     (rsp_valid_qs)
  );




  logic [17:0] addr_hit;
  always_comb begin
    addr_hit = '0;
    addr_hit[ 0] = (reg_addr == ETH_IDMA_MACLO_ADDR_OFFSET);
    addr_hit[ 1] = (reg_addr == ETH_IDMA_MACHI_MDIO_OFFSET);
    addr_hit[ 2] = (reg_addr == ETH_IDMA_TX_FCS_OFFSET);
    addr_hit[ 3] = (reg_addr == ETH_IDMA_RX_FCS_OFFSET);
    addr_hit[ 4] = (reg_addr == ETH_IDMA_SRC_ADDR_OFFSET);
    addr_hit[ 5] = (reg_addr == ETH_IDMA_DST_ADDR_OFFSET);
    addr_hit[ 6] = (reg_addr == ETH_IDMA_LENGTH_OFFSET);
    addr_hit[ 7] = (reg_addr == ETH_IDMA_SRC_PROTOCOL_OFFSET);
    addr_hit[ 8] = (reg_addr == ETH_IDMA_DST_PROTOCOL_OFFSET);
    addr_hit[ 9] = (reg_addr == ETH_IDMA_AXI_ID_OFFSET);
    addr_hit[10] = (reg_addr == ETH_IDMA_OPT_SRC_OFFSET);
    addr_hit[11] = (reg_addr == ETH_IDMA_OPT_DST_OFFSET);
    addr_hit[12] = (reg_addr == ETH_IDMA_BEO_OFFSET);
    addr_hit[13] = (reg_addr == ETH_IDMA_LAST_OFFSET);
    addr_hit[14] = (reg_addr == ETH_IDMA_REQ_VALID_OFFSET);
    addr_hit[15] = (reg_addr == ETH_IDMA_REQ_READY_OFFSET);
    addr_hit[16] = (reg_addr == ETH_IDMA_RSP_READY_OFFSET);
    addr_hit[17] = (reg_addr == ETH_IDMA_RSP_VALID_OFFSET);
  end

  assign addrmiss = (reg_re || reg_we) ? ~|addr_hit : 1'b0 ;

  // Check sub-word write is permitted
  always_comb begin
    wr_err = (reg_we &
              ((addr_hit[ 0] & (|(ETH_IDMA_PERMIT[ 0] & ~reg_be))) |
               (addr_hit[ 1] & (|(ETH_IDMA_PERMIT[ 1] & ~reg_be))) |
               (addr_hit[ 2] & (|(ETH_IDMA_PERMIT[ 2] & ~reg_be))) |
               (addr_hit[ 3] & (|(ETH_IDMA_PERMIT[ 3] & ~reg_be))) |
               (addr_hit[ 4] & (|(ETH_IDMA_PERMIT[ 4] & ~reg_be))) |
               (addr_hit[ 5] & (|(ETH_IDMA_PERMIT[ 5] & ~reg_be))) |
               (addr_hit[ 6] & (|(ETH_IDMA_PERMIT[ 6] & ~reg_be))) |
               (addr_hit[ 7] & (|(ETH_IDMA_PERMIT[ 7] & ~reg_be))) |
               (addr_hit[ 8] & (|(ETH_IDMA_PERMIT[ 8] & ~reg_be))) |
               (addr_hit[ 9] & (|(ETH_IDMA_PERMIT[ 9] & ~reg_be))) |
               (addr_hit[10] & (|(ETH_IDMA_PERMIT[10] & ~reg_be))) |
               (addr_hit[11] & (|(ETH_IDMA_PERMIT[11] & ~reg_be))) |
               (addr_hit[12] & (|(ETH_IDMA_PERMIT[12] & ~reg_be))) |
               (addr_hit[13] & (|(ETH_IDMA_PERMIT[13] & ~reg_be))) |
               (addr_hit[14] & (|(ETH_IDMA_PERMIT[14] & ~reg_be))) |
               (addr_hit[15] & (|(ETH_IDMA_PERMIT[15] & ~reg_be))) |
               (addr_hit[16] & (|(ETH_IDMA_PERMIT[16] & ~reg_be))) |
               (addr_hit[17] & (|(ETH_IDMA_PERMIT[17] & ~reg_be)))));
  end

  assign maclo_addr_we = addr_hit[0] & reg_we & !reg_error;
  assign maclo_addr_wd = reg_wdata[31:0];

  assign machi_mdio_upper_mac_address_we = addr_hit[1] & reg_we & !reg_error;
  assign machi_mdio_upper_mac_address_wd = reg_wdata[15:0];

  assign machi_mdio_promiscuous_we = addr_hit[1] & reg_we & !reg_error;
  assign machi_mdio_promiscuous_wd = reg_wdata[16];

  assign machi_mdio_phy_mdclk_we = addr_hit[1] & reg_we & !reg_error;
  assign machi_mdio_phy_mdclk_wd = reg_wdata[17];

  assign machi_mdio_phy_mdio_o_we = addr_hit[1] & reg_we & !reg_error;
  assign machi_mdio_phy_mdio_o_wd = reg_wdata[18];

  assign machi_mdio_phy_mdio_oe_we = addr_hit[1] & reg_we & !reg_error;
  assign machi_mdio_phy_mdio_oe_wd = reg_wdata[19];

  assign src_addr_we = addr_hit[4] & reg_we & !reg_error;
  assign src_addr_wd = reg_wdata[31:0];

  assign dst_addr_we = addr_hit[5] & reg_we & !reg_error;
  assign dst_addr_wd = reg_wdata[31:0];

  assign length_we = addr_hit[6] & reg_we & !reg_error;
  assign length_wd = reg_wdata[31:0];

  assign src_protocol_we = addr_hit[7] & reg_we & !reg_error;
  assign src_protocol_wd = reg_wdata[2:0];

  assign dst_protocol_we = addr_hit[8] & reg_we & !reg_error;
  assign dst_protocol_wd = reg_wdata[2:0];

  assign axi_id_we = addr_hit[9] & reg_we & !reg_error;
  assign axi_id_wd = reg_wdata[0];

  assign opt_src_burst_we = addr_hit[10] & reg_we & !reg_error;
  assign opt_src_burst_wd = reg_wdata[1:0];

  assign opt_src_cache_we = addr_hit[10] & reg_we & !reg_error;
  assign opt_src_cache_wd = reg_wdata[5:2];

  assign opt_src_lock_we = addr_hit[10] & reg_we & !reg_error;
  assign opt_src_lock_wd = reg_wdata[6];

  assign opt_src_prot_we = addr_hit[10] & reg_we & !reg_error;
  assign opt_src_prot_wd = reg_wdata[9:7];

  assign opt_src_qos_we = addr_hit[10] & reg_we & !reg_error;
  assign opt_src_qos_wd = reg_wdata[13:10];

  assign opt_src_region_we = addr_hit[10] & reg_we & !reg_error;
  assign opt_src_region_wd = reg_wdata[17:14];

  assign opt_dst_burst_we = addr_hit[11] & reg_we & !reg_error;
  assign opt_dst_burst_wd = reg_wdata[1:0];

  assign opt_dst_cache_we = addr_hit[11] & reg_we & !reg_error;
  assign opt_dst_cache_wd = reg_wdata[5:2];

  assign opt_dst_lock_we = addr_hit[11] & reg_we & !reg_error;
  assign opt_dst_lock_wd = reg_wdata[6];

  assign opt_dst_prot_we = addr_hit[11] & reg_we & !reg_error;
  assign opt_dst_prot_wd = reg_wdata[9:7];

  assign opt_dst_qos_we = addr_hit[11] & reg_we & !reg_error;
  assign opt_dst_qos_wd = reg_wdata[13:10];

  assign opt_dst_region_we = addr_hit[11] & reg_we & !reg_error;
  assign opt_dst_region_wd = reg_wdata[17:14];

  assign beo_decouple_aw_we = addr_hit[12] & reg_we & !reg_error;
  assign beo_decouple_aw_wd = reg_wdata[0];

  assign beo_decouple_rw_we = addr_hit[12] & reg_we & !reg_error;
  assign beo_decouple_rw_wd = reg_wdata[1];

  assign beo_src_max_llen_we = addr_hit[12] & reg_we & !reg_error;
  assign beo_src_max_llen_wd = reg_wdata[4:2];

  assign beo_dst_max_llen_we = addr_hit[12] & reg_we & !reg_error;
  assign beo_dst_max_llen_wd = reg_wdata[7:5];

  assign beo_src_reduce_len_we = addr_hit[12] & reg_we & !reg_error;
  assign beo_src_reduce_len_wd = reg_wdata[8];

  assign beo_dst_reduce_len_we = addr_hit[12] & reg_we & !reg_error;
  assign beo_dst_reduce_len_wd = reg_wdata[9];

  assign last_we = addr_hit[13] & reg_we & !reg_error;
  assign last_wd = reg_wdata[0];

  assign req_valid_we = addr_hit[14] & reg_we & !reg_error;
  assign req_valid_wd = reg_wdata[0];

  assign rsp_ready_we = addr_hit[16] & reg_we & !reg_error;
  assign rsp_ready_wd = reg_wdata[0];

  // Read data return
  always_comb begin
    reg_rdata_next = '0;
    unique case (1'b1)
      addr_hit[0]: begin
        reg_rdata_next[31:0] = maclo_addr_qs;
      end

      addr_hit[1]: begin
        reg_rdata_next[15:0] = machi_mdio_upper_mac_address_qs;
        reg_rdata_next[16] = machi_mdio_promiscuous_qs;
        reg_rdata_next[17] = machi_mdio_phy_mdclk_qs;
        reg_rdata_next[18] = machi_mdio_phy_mdio_o_qs;
        reg_rdata_next[19] = machi_mdio_phy_mdio_oe_qs;
      end

      addr_hit[2]: begin
        reg_rdata_next[31:0] = tx_fcs_qs;
      end

      addr_hit[3]: begin
        reg_rdata_next[31:0] = rx_fcs_qs;
      end

      addr_hit[4]: begin
        reg_rdata_next[31:0] = src_addr_qs;
      end

      addr_hit[5]: begin
        reg_rdata_next[31:0] = dst_addr_qs;
      end

      addr_hit[6]: begin
        reg_rdata_next[31:0] = length_qs;
      end

      addr_hit[7]: begin
        reg_rdata_next[2:0] = src_protocol_qs;
      end

      addr_hit[8]: begin
        reg_rdata_next[2:0] = dst_protocol_qs;
      end

      addr_hit[9]: begin
        reg_rdata_next[0] = axi_id_qs;
      end

      addr_hit[10]: begin
        reg_rdata_next[1:0] = opt_src_burst_qs;
        reg_rdata_next[5:2] = opt_src_cache_qs;
        reg_rdata_next[6] = opt_src_lock_qs;
        reg_rdata_next[9:7] = opt_src_prot_qs;
        reg_rdata_next[13:10] = opt_src_qos_qs;
        reg_rdata_next[17:14] = opt_src_region_qs;
      end

      addr_hit[11]: begin
        reg_rdata_next[1:0] = opt_dst_burst_qs;
        reg_rdata_next[5:2] = opt_dst_cache_qs;
        reg_rdata_next[6] = opt_dst_lock_qs;
        reg_rdata_next[9:7] = opt_dst_prot_qs;
        reg_rdata_next[13:10] = opt_dst_qos_qs;
        reg_rdata_next[17:14] = opt_dst_region_qs;
      end

      addr_hit[12]: begin
        reg_rdata_next[0] = beo_decouple_aw_qs;
        reg_rdata_next[1] = beo_decouple_rw_qs;
        reg_rdata_next[4:2] = beo_src_max_llen_qs;
        reg_rdata_next[7:5] = beo_dst_max_llen_qs;
        reg_rdata_next[8] = beo_src_reduce_len_qs;
        reg_rdata_next[9] = beo_dst_reduce_len_qs;
      end

      addr_hit[13]: begin
        reg_rdata_next[0] = last_qs;
      end

      addr_hit[14]: begin
        reg_rdata_next[0] = req_valid_qs;
      end

      addr_hit[15]: begin
        reg_rdata_next[0] = req_ready_qs;
      end

      addr_hit[16]: begin
        reg_rdata_next[0] = rsp_ready_qs;
      end

      addr_hit[17]: begin
        reg_rdata_next[0] = rsp_valid_qs;
      end

      default: begin
        reg_rdata_next = '1;
      end
    endcase
  end

  // Unused signal tieoff

  // wdata / byte enable are not always fully used
  // add a blanket unused statement to handle lint waivers
  logic unused_wdata;
  logic unused_be;
  assign unused_wdata = ^reg_wdata;
  assign unused_be = ^reg_be;

  // Assertions for Register Interface
  `ASSERT(en2addrHit, (reg_we || reg_re) |-> $onehot0(addr_hit))

endmodule

module eth_idma_reg_top_intf
#(
  parameter int AW = 8,
  localparam int DW = 64
) (
  input logic clk_i,
  input logic rst_ni,
  REG_BUS.in  regbus_slave,
  // To HW
  output eth_idma_reg_pkg::eth_idma_reg2hw_t reg2hw, // Write
  input  eth_idma_reg_pkg::eth_idma_hw2reg_t hw2reg, // Read
  // Config
  input devmode_i // If 1, explicit error return for unmapped register access
);
 localparam int unsigned STRB_WIDTH = DW/8;

`include "register_interface/typedef.svh"
`include "register_interface/assign.svh"

  // Define structs for reg_bus
  typedef logic [AW-1:0] addr_t;
  typedef logic [DW-1:0] data_t;
  typedef logic [STRB_WIDTH-1:0] strb_t;
  `REG_BUS_TYPEDEF_ALL(reg_bus, addr_t, data_t, strb_t)

  reg_bus_req_t s_reg_req;
  reg_bus_rsp_t s_reg_rsp;
  
  // Assign SV interface to structs
  `REG_BUS_ASSIGN_TO_REQ(s_reg_req, regbus_slave)
  `REG_BUS_ASSIGN_FROM_RSP(regbus_slave, s_reg_rsp)

  

  eth_idma_reg_top #(
    .reg_req_t(reg_bus_req_t),
    .reg_rsp_t(reg_bus_rsp_t),
    .AW(AW)
  ) i_regs (
    .clk_i,
    .rst_ni,
    .reg_req_i(s_reg_req),
    .reg_rsp_o(s_reg_rsp),
    .reg2hw, // Write
    .hw2reg, // Read
    .devmode_i
  );
  
endmodule


