onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /eth_tb/s_clk
add wave -noupdate /eth_tb/s_clk_200MHz
add wave -noupdate /eth_tb/s_clk_125MHz_0
add wave -noupdate /eth_tb/s_clk_125MHz_90
add wave -noupdate /eth_tb/s_rst_n
add wave -noupdate /eth_tb/done
add wave -noupdate /eth_tb/eth_rxck
add wave -noupdate /eth_tb/eth_rxctl
add wave -noupdate /eth_tb/eth_rxd
add wave -noupdate /eth_tb/eth_txck
add wave -noupdate /eth_tb/eth_txctl
add wave -noupdate /eth_tb/eth_txd
add wave -noupdate /eth_tb/eth_tx_rst_n
add wave -noupdate /eth_tb/eth_rx_rst_n
add wave -noupdate /eth_tb/rx_read_data
add wave -noupdate /eth_tb/tx_complete
add wave -noupdate /eth_tb/en_rx_memw
add wave -noupdate -group eth_rgmii_tx /eth_tb/i_eth_rgmii_tx/clk_i
add wave -noupdate -group eth_rgmii_tx /eth_tb/i_eth_rgmii_tx/clk_200MHz_i
add wave -noupdate -group eth_rgmii_tx /eth_tb/i_eth_rgmii_tx/rst_ni
add wave -noupdate -group eth_rgmii_tx /eth_tb/i_eth_rgmii_tx/eth_clk_i
add wave -noupdate -group eth_rgmii_tx /eth_tb/i_eth_rgmii_tx/eth_rxck
add wave -noupdate -group eth_rgmii_tx /eth_tb/i_eth_rgmii_tx/eth_rxctl
add wave -noupdate -group eth_rgmii_tx /eth_tb/i_eth_rgmii_tx/eth_rxd
add wave -noupdate -group eth_rgmii_tx /eth_tb/i_eth_rgmii_tx/eth_txck
add wave -noupdate -group eth_rgmii_tx /eth_tb/i_eth_rgmii_tx/eth_txctl
add wave -noupdate -group eth_rgmii_tx /eth_tb/i_eth_rgmii_tx/eth_txd
add wave -noupdate -group eth_rgmii_tx /eth_tb/i_eth_rgmii_tx/eth_rst_n
add wave -noupdate -group eth_rgmii_tx /eth_tb/i_eth_rgmii_tx/phy_tx_clk_i
add wave -noupdate -group eth_rgmii_tx /eth_tb/i_eth_rgmii_tx/eth_irq
add wave -noupdate -group eth_rgmii_tx /eth_tb/i_eth_rgmii_tx/eth_en
add wave -noupdate -group eth_rgmii_tx /eth_tb/i_eth_rgmii_tx/eth_we
add wave -noupdate -group eth_rgmii_tx /eth_tb/i_eth_rgmii_tx/eth_int_n
add wave -noupdate -group eth_rgmii_tx /eth_tb/i_eth_rgmii_tx/eth_pme_n
add wave -noupdate -group eth_rgmii_tx /eth_tb/i_eth_rgmii_tx/eth_mdio_i
add wave -noupdate -group eth_rgmii_tx /eth_tb/i_eth_rgmii_tx/eth_mdio_o
add wave -noupdate -group eth_rgmii_tx /eth_tb/i_eth_rgmii_tx/eth_mdio_oe
add wave -noupdate -group eth_rgmii_tx /eth_tb/i_eth_rgmii_tx/eth_addr
add wave -noupdate -group eth_rgmii_tx /eth_tb/i_eth_rgmii_tx/eth_wrdata
add wave -noupdate -group eth_rgmii_tx /eth_tb/i_eth_rgmii_tx/eth_rdata
add wave -noupdate -group eth_rgmii_tx /eth_tb/i_eth_rgmii_tx/eth_be
add wave -noupdate -group eth_rgmii_tx /eth_tb/i_eth_rgmii_tx/eth_mdc
add wave -noupdate -group framing_top_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/msoc_clk
add wave -noupdate -group framing_top_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/core_lsu_addr
add wave -noupdate -group framing_top_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/core_lsu_wdata
add wave -noupdate -group framing_top_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/core_lsu_be
add wave -noupdate -group framing_top_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/ce_d
add wave -noupdate -group framing_top_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/we_d
add wave -noupdate -group framing_top_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/framing_sel
add wave -noupdate -group framing_top_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/framing_rdata
add wave -noupdate -group framing_top_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/clk_int
add wave -noupdate -group framing_top_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/rst_int
add wave -noupdate -group framing_top_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/clk90_int
add wave -noupdate -group framing_top_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/clk_200_int
add wave -noupdate -group framing_top_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/phy_rx_clk
add wave -noupdate -group framing_top_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/phy_rxd
add wave -noupdate -group framing_top_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/phy_rx_ctl
add wave -noupdate -group framing_top_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/phy_tx_clk
add wave -noupdate -group framing_top_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/phy_txd
add wave -noupdate -group framing_top_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/phy_tx_ctl
add wave -noupdate -group framing_top_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/phy_reset_n
add wave -noupdate -group framing_top_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/phy_int_n
add wave -noupdate -group framing_top_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/phy_pme_n
add wave -noupdate -group framing_top_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/phy_mdio_i
add wave -noupdate -group framing_top_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/phy_mdio_o
add wave -noupdate -group framing_top_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/phy_mdio_oe
add wave -noupdate -group framing_top_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/phy_mdc
add wave -noupdate -group framing_top_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/eth_irq
add wave -noupdate -group framing_top_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/core_lsu_addr_dly
add wave -noupdate -group framing_top_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/tx_enable_i
add wave -noupdate -group framing_top_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/mac_gmii_tx_en
add wave -noupdate -group framing_top_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/mac_address
add wave -noupdate -group framing_top_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/rx_dest_mac
add wave -noupdate -group framing_top_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/tx_frame_addr
add wave -noupdate -group framing_top_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/tx_packet_length
add wave -noupdate -group framing_top_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/axis_tx_frame_size
add wave -noupdate -group framing_top_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/ce_d_dly
add wave -noupdate -group framing_top_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/avail
add wave -noupdate -group framing_top_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/framing_rdata_pkt
add wave -noupdate -group framing_top_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/framing_wdata_pkt
add wave -noupdate -group framing_top_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/tx_enable_dly
add wave -noupdate -group framing_top_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/firstbuf
add wave -noupdate -group framing_top_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/nextbuf
add wave -noupdate -group framing_top_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/lastbuf
add wave -noupdate -group framing_top_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/last
add wave -noupdate -group framing_top_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/byte_sync
add wave -noupdate -group framing_top_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/sync
add wave -noupdate -group framing_top_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/irq_en
add wave -noupdate -group framing_top_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/tx_busy
add wave -noupdate -group framing_top_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/m_enb
add wave -noupdate -group framing_top_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/phy_mdclk
add wave -noupdate -group framing_top_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/cooked
add wave -noupdate -group framing_top_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/tx_enable_old
add wave -noupdate -group framing_top_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/loopback
add wave -noupdate -group framing_top_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/promiscuous
add wave -noupdate -group framing_top_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/spare
add wave -noupdate -group framing_top_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/rx_addr_axis
add wave -noupdate -group framing_top_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/tx_axis_tvalid
add wave -noupdate -group framing_top_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/tx_axis_tvalid_dly
add wave -noupdate -group framing_top_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/tx_axis_tlast
add wave -noupdate -group framing_top_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/tx_axis_tdata
add wave -noupdate -group framing_top_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/tx_axis_tready
add wave -noupdate -group framing_top_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/tx_axis_tuser
add wave -noupdate -group framing_top_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/rx_axis_tdata
add wave -noupdate -group framing_top_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/rx_axis_tvalid
add wave -noupdate -group framing_top_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/rx_axis_tlast
add wave -noupdate -group framing_top_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/rx_axis_tuser
add wave -noupdate -group framing_top_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/tx_fcs_reg_rev
add wave -noupdate -group framing_top_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/rx_fcs_reg_rev
add wave -noupdate -group framing_top_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/rx_wr
add wave -noupdate -group framing_top_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/douta
add wave -noupdate -group framing_top_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/tx_fcs_reg
add wave -noupdate -group framing_top_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/rx_fcs_reg
add wave -noupdate -group dualmem_widen_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/RAMB16_inst_tx/clka
add wave -noupdate -group dualmem_widen_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/RAMB16_inst_tx/clkb
add wave -noupdate -group dualmem_widen_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/RAMB16_inst_tx/dina
add wave -noupdate -group dualmem_widen_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/RAMB16_inst_tx/dinb
add wave -noupdate -group dualmem_widen_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/RAMB16_inst_tx/addra
add wave -noupdate -group dualmem_widen_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/RAMB16_inst_tx/addrb
add wave -noupdate -group dualmem_widen_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/RAMB16_inst_tx/wea
add wave -noupdate -group dualmem_widen_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/RAMB16_inst_tx/web
add wave -noupdate -group dualmem_widen_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/RAMB16_inst_tx/ena
add wave -noupdate -group dualmem_widen_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/RAMB16_inst_tx/enb
add wave -noupdate -group dualmem_widen_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/RAMB16_inst_tx/douta
add wave -noupdate -group dualmem_widen_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/RAMB16_inst_tx/doutb
add wave -noupdate -group dualmem_widen_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/RAMB16_inst_tx/dout
add wave -noupdate -group mem0_tx {/eth_tb/i_eth_rgmii_tx/eth_rgmii/RAMB16_inst_tx/genblk1[0]/GF22_wrap_tx_inst/GF22_inst/CLK_A}
add wave -noupdate -group mem0_tx {/eth_tb/i_eth_rgmii_tx/eth_rgmii/RAMB16_inst_tx/genblk1[0]/GF22_wrap_tx_inst/GF22_inst/CLK_B}
add wave -noupdate -group mem0_tx {/eth_tb/i_eth_rgmii_tx/eth_rgmii/RAMB16_inst_tx/genblk1[0]/GF22_wrap_tx_inst/GF22_inst/CEN_A}
add wave -noupdate -group mem0_tx {/eth_tb/i_eth_rgmii_tx/eth_rgmii/RAMB16_inst_tx/genblk1[0]/GF22_wrap_tx_inst/GF22_inst/CEN_B}
add wave -noupdate -group mem0_tx {/eth_tb/i_eth_rgmii_tx/eth_rgmii/RAMB16_inst_tx/genblk1[0]/GF22_wrap_tx_inst/GF22_inst/AW_A}
add wave -noupdate -group mem0_tx {/eth_tb/i_eth_rgmii_tx/eth_rgmii/RAMB16_inst_tx/genblk1[0]/GF22_wrap_tx_inst/GF22_inst/AC_A}
add wave -noupdate -group mem0_tx {/eth_tb/i_eth_rgmii_tx/eth_rgmii/RAMB16_inst_tx/genblk1[0]/GF22_wrap_tx_inst/GF22_inst/AW_B}
add wave -noupdate -group mem0_tx {/eth_tb/i_eth_rgmii_tx/eth_rgmii/RAMB16_inst_tx/genblk1[0]/GF22_wrap_tx_inst/GF22_inst/AC_B}
add wave -noupdate -group mem0_tx {/eth_tb/i_eth_rgmii_tx/eth_rgmii/RAMB16_inst_tx/genblk1[0]/GF22_wrap_tx_inst/GF22_inst/D}
add wave -noupdate -group mem0_tx {/eth_tb/i_eth_rgmii_tx/eth_rgmii/RAMB16_inst_tx/genblk1[0]/GF22_wrap_tx_inst/GF22_inst/BW}
add wave -noupdate -group mem0_tx {/eth_tb/i_eth_rgmii_tx/eth_rgmii/RAMB16_inst_tx/genblk1[0]/GF22_wrap_tx_inst/GF22_inst/Q}
add wave -noupdate -group mem0_tx {/eth_tb/i_eth_rgmii_tx/eth_rgmii/RAMB16_inst_tx/genblk1[0]/GF22_wrap_tx_inst/GF22_inst/mem0/array}
add wave -noupdate -group mem1_tx {/eth_tb/i_eth_rgmii_tx/eth_rgmii/RAMB16_inst_tx/genblk1[1]/GF22_wrap_tx_inst/GF22_inst/CLK_A}
add wave -noupdate -group mem1_tx {/eth_tb/i_eth_rgmii_tx/eth_rgmii/RAMB16_inst_tx/genblk1[1]/GF22_wrap_tx_inst/GF22_inst/CLK_B}
add wave -noupdate -group mem1_tx {/eth_tb/i_eth_rgmii_tx/eth_rgmii/RAMB16_inst_tx/genblk1[1]/GF22_wrap_tx_inst/GF22_inst/CEN_A}
add wave -noupdate -group mem1_tx {/eth_tb/i_eth_rgmii_tx/eth_rgmii/RAMB16_inst_tx/genblk1[1]/GF22_wrap_tx_inst/GF22_inst/CEN_B}
add wave -noupdate -group mem1_tx {/eth_tb/i_eth_rgmii_tx/eth_rgmii/RAMB16_inst_tx/genblk1[1]/GF22_wrap_tx_inst/GF22_inst/AW_A}
add wave -noupdate -group mem1_tx {/eth_tb/i_eth_rgmii_tx/eth_rgmii/RAMB16_inst_tx/genblk1[1]/GF22_wrap_tx_inst/GF22_inst/AC_A}
add wave -noupdate -group mem1_tx {/eth_tb/i_eth_rgmii_tx/eth_rgmii/RAMB16_inst_tx/genblk1[1]/GF22_wrap_tx_inst/GF22_inst/AW_B}
add wave -noupdate -group mem1_tx {/eth_tb/i_eth_rgmii_tx/eth_rgmii/RAMB16_inst_tx/genblk1[1]/GF22_wrap_tx_inst/GF22_inst/AC_B}
add wave -noupdate -group mem1_tx {/eth_tb/i_eth_rgmii_tx/eth_rgmii/RAMB16_inst_tx/genblk1[1]/GF22_wrap_tx_inst/GF22_inst/D}
add wave -noupdate -group mem1_tx {/eth_tb/i_eth_rgmii_tx/eth_rgmii/RAMB16_inst_tx/genblk1[1]/GF22_wrap_tx_inst/GF22_inst/BW}
add wave -noupdate -group mem1_tx {/eth_tb/i_eth_rgmii_tx/eth_rgmii/RAMB16_inst_tx/genblk1[1]/GF22_wrap_tx_inst/GF22_inst/Q}
add wave -noupdate -group mem1_tx {/eth_tb/i_eth_rgmii_tx/eth_rgmii/RAMB16_inst_tx/genblk1[1]/GF22_wrap_tx_inst/GF22_inst/mem0/array}
add wave -noupdate -group eth_rgmii_rx /eth_tb/i_eth_rgmii_rx/clk_i
add wave -noupdate -group eth_rgmii_rx /eth_tb/i_eth_rgmii_rx/clk_200MHz_i
add wave -noupdate -group eth_rgmii_rx /eth_tb/i_eth_rgmii_rx/rst_ni
add wave -noupdate -group eth_rgmii_rx /eth_tb/i_eth_rgmii_rx/eth_clk_i
add wave -noupdate -group eth_rgmii_rx /eth_tb/i_eth_rgmii_rx/eth_rxck
add wave -noupdate -group eth_rgmii_rx /eth_tb/i_eth_rgmii_rx/eth_rxctl
add wave -noupdate -group eth_rgmii_rx /eth_tb/i_eth_rgmii_rx/eth_rxd
add wave -noupdate -group eth_rgmii_rx /eth_tb/i_eth_rgmii_rx/eth_txck
add wave -noupdate -group eth_rgmii_rx /eth_tb/i_eth_rgmii_rx/eth_txctl
add wave -noupdate -group eth_rgmii_rx /eth_tb/i_eth_rgmii_rx/eth_txd
add wave -noupdate -group eth_rgmii_rx /eth_tb/i_eth_rgmii_rx/eth_rst_n
add wave -noupdate -group eth_rgmii_rx /eth_tb/i_eth_rgmii_rx/phy_tx_clk_i
add wave -noupdate -group eth_rgmii_rx /eth_tb/i_eth_rgmii_rx/eth_irq
add wave -noupdate -group eth_rgmii_rx /eth_tb/i_eth_rgmii_rx/eth_en
add wave -noupdate -group eth_rgmii_rx /eth_tb/i_eth_rgmii_rx/eth_we
add wave -noupdate -group eth_rgmii_rx /eth_tb/i_eth_rgmii_rx/eth_int_n
add wave -noupdate -group eth_rgmii_rx /eth_tb/i_eth_rgmii_rx/eth_pme_n
add wave -noupdate -group eth_rgmii_rx /eth_tb/i_eth_rgmii_rx/eth_mdio_i
add wave -noupdate -group eth_rgmii_rx /eth_tb/i_eth_rgmii_rx/eth_mdio_o
add wave -noupdate -group eth_rgmii_rx /eth_tb/i_eth_rgmii_rx/eth_mdio_oe
add wave -noupdate -group eth_rgmii_rx /eth_tb/i_eth_rgmii_rx/eth_addr
add wave -noupdate -group eth_rgmii_rx /eth_tb/i_eth_rgmii_rx/eth_wrdata
add wave -noupdate -group eth_rgmii_rx /eth_tb/i_eth_rgmii_rx/eth_rdata
add wave -noupdate -group eth_rgmii_rx /eth_tb/i_eth_rgmii_rx/eth_be
add wave -noupdate -group eth_rgmii_rx /eth_tb/i_eth_rgmii_rx/eth_mdc
add wave -noupdate -group framing_top_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/msoc_clk
add wave -noupdate -group framing_top_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/core_lsu_addr
add wave -noupdate -group framing_top_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/core_lsu_wdata
add wave -noupdate -group framing_top_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/core_lsu_be
add wave -noupdate -group framing_top_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/ce_d
add wave -noupdate -group framing_top_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/we_d
add wave -noupdate -group framing_top_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/framing_sel
add wave -noupdate -group framing_top_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/framing_rdata
add wave -noupdate -group framing_top_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/clk_int
add wave -noupdate -group framing_top_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/rst_int
add wave -noupdate -group framing_top_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/clk90_int
add wave -noupdate -group framing_top_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/clk_200_int
add wave -noupdate -group framing_top_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/phy_rx_clk
add wave -noupdate -group framing_top_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/phy_rxd
add wave -noupdate -group framing_top_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/phy_rx_ctl
add wave -noupdate -group framing_top_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/phy_tx_clk
add wave -noupdate -group framing_top_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/phy_txd
add wave -noupdate -group framing_top_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/phy_tx_ctl
add wave -noupdate -group framing_top_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/phy_reset_n
add wave -noupdate -group framing_top_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/phy_int_n
add wave -noupdate -group framing_top_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/phy_pme_n
add wave -noupdate -group framing_top_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/phy_mdio_i
add wave -noupdate -group framing_top_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/phy_mdio_o
add wave -noupdate -group framing_top_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/phy_mdio_oe
add wave -noupdate -group framing_top_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/phy_mdc
add wave -noupdate -group framing_top_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/eth_irq
add wave -noupdate -group framing_top_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/core_lsu_addr_dly
add wave -noupdate -group framing_top_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/tx_enable_i
add wave -noupdate -group framing_top_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/mac_gmii_tx_en
add wave -noupdate -group framing_top_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/mac_address
add wave -noupdate -group framing_top_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/rx_dest_mac
add wave -noupdate -group framing_top_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/tx_frame_addr
add wave -noupdate -group framing_top_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/tx_packet_length
add wave -noupdate -group framing_top_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/axis_tx_frame_size
add wave -noupdate -group framing_top_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/ce_d_dly
add wave -noupdate -group framing_top_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/avail
add wave -noupdate -group framing_top_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/framing_rdata_pkt
add wave -noupdate -group framing_top_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/framing_wdata_pkt
add wave -noupdate -group framing_top_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/tx_enable_dly
add wave -noupdate -group framing_top_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/firstbuf
add wave -noupdate -group framing_top_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/nextbuf
add wave -noupdate -group framing_top_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/lastbuf
add wave -noupdate -group framing_top_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/last
add wave -noupdate -group framing_top_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/byte_sync
add wave -noupdate -group framing_top_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/sync
add wave -noupdate -group framing_top_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/irq_en
add wave -noupdate -group framing_top_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/tx_busy
add wave -noupdate -group framing_top_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/m_enb
add wave -noupdate -group framing_top_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/phy_mdclk
add wave -noupdate -group framing_top_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/cooked
add wave -noupdate -group framing_top_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/tx_enable_old
add wave -noupdate -group framing_top_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/loopback
add wave -noupdate -group framing_top_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/promiscuous
add wave -noupdate -group framing_top_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/spare
add wave -noupdate -group framing_top_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/rx_addr_axis
add wave -noupdate -group framing_top_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/tx_axis_tvalid
add wave -noupdate -group framing_top_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/tx_axis_tvalid_dly
add wave -noupdate -group framing_top_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/tx_axis_tlast
add wave -noupdate -group framing_top_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/tx_axis_tdata
add wave -noupdate -group framing_top_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/tx_axis_tready
add wave -noupdate -group framing_top_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/tx_axis_tuser
add wave -noupdate -group framing_top_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/rx_axis_tdata
add wave -noupdate -group framing_top_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/rx_axis_tvalid
add wave -noupdate -group framing_top_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/rx_axis_tlast
add wave -noupdate -group framing_top_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/rx_axis_tuser
add wave -noupdate -group framing_top_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/tx_fcs_reg_rev
add wave -noupdate -group framing_top_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/rx_fcs_reg_rev
add wave -noupdate -group framing_top_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/rx_wr
add wave -noupdate -group framing_top_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/douta
add wave -noupdate -group framing_top_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/tx_fcs_reg
add wave -noupdate -group framing_top_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/rx_fcs_reg
add wave -noupdate -group dualmem_widen8_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/RAMB16_inst_rx/clka
add wave -noupdate -group dualmem_widen8_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/RAMB16_inst_rx/clkb
add wave -noupdate -group dualmem_widen8_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/RAMB16_inst_rx/dina
add wave -noupdate -group dualmem_widen8_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/RAMB16_inst_rx/dinb
add wave -noupdate -group dualmem_widen8_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/RAMB16_inst_rx/addra
add wave -noupdate -group dualmem_widen8_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/RAMB16_inst_rx/addrb
add wave -noupdate -group dualmem_widen8_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/RAMB16_inst_rx/wea
add wave -noupdate -group dualmem_widen8_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/RAMB16_inst_rx/web
add wave -noupdate -group dualmem_widen8_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/RAMB16_inst_rx/ena
add wave -noupdate -group dualmem_widen8_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/RAMB16_inst_rx/enb
add wave -noupdate -group dualmem_widen8_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/RAMB16_inst_rx/douta
add wave -noupdate -group dualmem_widen8_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/RAMB16_inst_rx/doutb
add wave -noupdate -group dualmem_widen8_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/RAMB16_inst_rx/dout0
add wave -noupdate -group dualmem_widen8_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/RAMB16_inst_rx/dout1
add wave -noupdate -group dualmem_widen8_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/RAMB16_inst_rx/we0
add wave -noupdate -group dualmem_widen8_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/RAMB16_inst_rx/we1
add wave -noupdate -group dualmem_widen8_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/RAMB16_inst_rx/en0
add wave -noupdate -group dualmem_widen8_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/RAMB16_inst_rx/en1
add wave -noupdate -group dualmem_widen8_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/RAMB16_inst_rx/din0
add wave -noupdate -group dualmem_widen8_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/RAMB16_inst_rx/din1
add wave -noupdate -group dualmem_widen8_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/RAMB16_inst_rx/addra_dly
add wave -noupdate -group dualmem_widen8_rx /eth_tb/i_eth_rgmii_rx/eth_rgmii/RAMB16_inst_rx/addrb_dly
add wave -noupdate -group mem0_rx {/eth_tb/i_eth_rgmii_rx/eth_rgmii/RAMB16_inst_rx/genblk1[0]/GF22_wrap_rx_inst/GF22_inst/CLK_A}
add wave -noupdate -group mem0_rx {/eth_tb/i_eth_rgmii_rx/eth_rgmii/RAMB16_inst_rx/genblk1[0]/GF22_wrap_rx_inst/GF22_inst/CLK_B}
add wave -noupdate -group mem0_rx {/eth_tb/i_eth_rgmii_rx/eth_rgmii/RAMB16_inst_rx/genblk1[0]/GF22_wrap_rx_inst/GF22_inst/CEN_A}
add wave -noupdate -group mem0_rx {/eth_tb/i_eth_rgmii_rx/eth_rgmii/RAMB16_inst_rx/genblk1[0]/GF22_wrap_rx_inst/GF22_inst/CEN_B}
add wave -noupdate -group mem0_rx {/eth_tb/i_eth_rgmii_rx/eth_rgmii/RAMB16_inst_rx/genblk1[0]/GF22_wrap_rx_inst/GF22_inst/AW_A}
add wave -noupdate -group mem0_rx {/eth_tb/i_eth_rgmii_rx/eth_rgmii/RAMB16_inst_rx/genblk1[0]/GF22_wrap_rx_inst/GF22_inst/AC_A}
add wave -noupdate -group mem0_rx {/eth_tb/i_eth_rgmii_rx/eth_rgmii/RAMB16_inst_rx/genblk1[0]/GF22_wrap_rx_inst/GF22_inst/AW_B}
add wave -noupdate -group mem0_rx {/eth_tb/i_eth_rgmii_rx/eth_rgmii/RAMB16_inst_rx/genblk1[0]/GF22_wrap_rx_inst/GF22_inst/AC_B}
add wave -noupdate -group mem0_rx {/eth_tb/i_eth_rgmii_rx/eth_rgmii/RAMB16_inst_rx/genblk1[0]/GF22_wrap_rx_inst/GF22_inst/D}
add wave -noupdate -group mem0_rx {/eth_tb/i_eth_rgmii_rx/eth_rgmii/RAMB16_inst_rx/genblk1[0]/GF22_wrap_rx_inst/GF22_inst/BW}
add wave -noupdate -group mem0_rx {/eth_tb/i_eth_rgmii_rx/eth_rgmii/RAMB16_inst_rx/genblk1[0]/GF22_wrap_rx_inst/GF22_inst/Q}
add wave -noupdate -group mem0_rx {/eth_tb/i_eth_rgmii_rx/eth_rgmii/RAMB16_inst_rx/genblk1[0]/GF22_wrap_rx_inst/GF22_inst/mem0/array}
add wave -noupdate -group mem1_rx {/eth_tb/i_eth_rgmii_rx/eth_rgmii/RAMB16_inst_rx/genblk1[1]/GF22_wrap_rx_inst/GF22_inst/CLK_A}
add wave -noupdate -group mem1_rx {/eth_tb/i_eth_rgmii_rx/eth_rgmii/RAMB16_inst_rx/genblk1[1]/GF22_wrap_rx_inst/GF22_inst/CLK_B}
add wave -noupdate -group mem1_rx {/eth_tb/i_eth_rgmii_rx/eth_rgmii/RAMB16_inst_rx/genblk1[1]/GF22_wrap_rx_inst/GF22_inst/CEN_A}
add wave -noupdate -group mem1_rx {/eth_tb/i_eth_rgmii_rx/eth_rgmii/RAMB16_inst_rx/genblk1[1]/GF22_wrap_rx_inst/GF22_inst/CEN_B}
add wave -noupdate -group mem1_rx {/eth_tb/i_eth_rgmii_rx/eth_rgmii/RAMB16_inst_rx/genblk1[1]/GF22_wrap_rx_inst/GF22_inst/AW_A}
add wave -noupdate -group mem1_rx {/eth_tb/i_eth_rgmii_rx/eth_rgmii/RAMB16_inst_rx/genblk1[1]/GF22_wrap_rx_inst/GF22_inst/AC_A}
add wave -noupdate -group mem1_rx {/eth_tb/i_eth_rgmii_rx/eth_rgmii/RAMB16_inst_rx/genblk1[1]/GF22_wrap_rx_inst/GF22_inst/AW_B}
add wave -noupdate -group mem1_rx {/eth_tb/i_eth_rgmii_rx/eth_rgmii/RAMB16_inst_rx/genblk1[1]/GF22_wrap_rx_inst/GF22_inst/AC_B}
add wave -noupdate -group mem1_rx {/eth_tb/i_eth_rgmii_rx/eth_rgmii/RAMB16_inst_rx/genblk1[1]/GF22_wrap_rx_inst/GF22_inst/D}
add wave -noupdate -group mem1_rx {/eth_tb/i_eth_rgmii_rx/eth_rgmii/RAMB16_inst_rx/genblk1[1]/GF22_wrap_rx_inst/GF22_inst/BW}
add wave -noupdate -group mem1_rx {/eth_tb/i_eth_rgmii_rx/eth_rgmii/RAMB16_inst_rx/genblk1[1]/GF22_wrap_rx_inst/GF22_inst/Q}
add wave -noupdate -group mem1_rx {/eth_tb/i_eth_rgmii_rx/eth_rgmii/RAMB16_inst_rx/genblk1[1]/GF22_wrap_rx_inst/GF22_inst/mem0/array}
add wave -noupdate -group axis_gmii_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/eth_mac_1g_rgmii_inst/eth_mac_1g_inst/axis_gmii_tx_inst/clk
add wave -noupdate -group axis_gmii_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/eth_mac_1g_rgmii_inst/eth_mac_1g_inst/axis_gmii_tx_inst/rst
add wave -noupdate -group axis_gmii_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/eth_mac_1g_rgmii_inst/eth_mac_1g_inst/axis_gmii_tx_inst/s_axis_tdata
add wave -noupdate -group axis_gmii_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/eth_mac_1g_rgmii_inst/eth_mac_1g_inst/axis_gmii_tx_inst/s_axis_tvalid
add wave -noupdate -group axis_gmii_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/eth_mac_1g_rgmii_inst/eth_mac_1g_inst/axis_gmii_tx_inst/s_axis_tready
add wave -noupdate -group axis_gmii_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/eth_mac_1g_rgmii_inst/eth_mac_1g_inst/axis_gmii_tx_inst/s_axis_tlast
add wave -noupdate -group axis_gmii_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/eth_mac_1g_rgmii_inst/eth_mac_1g_inst/axis_gmii_tx_inst/s_axis_tuser
add wave -noupdate -group axis_gmii_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/eth_mac_1g_rgmii_inst/eth_mac_1g_inst/axis_gmii_tx_inst/gmii_txd
add wave -noupdate -group axis_gmii_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/eth_mac_1g_rgmii_inst/eth_mac_1g_inst/axis_gmii_tx_inst/gmii_tx_en
add wave -noupdate -group axis_gmii_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/eth_mac_1g_rgmii_inst/eth_mac_1g_inst/axis_gmii_tx_inst/gmii_tx_er
add wave -noupdate -group axis_gmii_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/eth_mac_1g_rgmii_inst/eth_mac_1g_inst/axis_gmii_tx_inst/ifg_delay
add wave -noupdate -group axis_gmii_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/eth_mac_1g_rgmii_inst/eth_mac_1g_inst/axis_gmii_tx_inst/fcs_reg
add wave -noupdate -group axis_gmii_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/eth_mac_1g_rgmii_inst/eth_mac_1g_inst/axis_gmii_tx_inst/clk_enable
add wave -noupdate -group axis_gmii_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/eth_mac_1g_rgmii_inst/eth_mac_1g_inst/axis_gmii_tx_inst/mii_select
add wave -noupdate -group axis_gmii_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/eth_mac_1g_rgmii_inst/eth_mac_1g_inst/axis_gmii_tx_inst/mii_odd_reg
add wave -noupdate -group axis_gmii_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/eth_mac_1g_rgmii_inst/eth_mac_1g_inst/axis_gmii_tx_inst/state_reg
add wave -noupdate -group axis_gmii_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/eth_mac_1g_rgmii_inst/eth_mac_1g_inst/axis_gmii_tx_inst/state_next
add wave -noupdate -group axis_gmii_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/eth_mac_1g_rgmii_inst/eth_mac_1g_inst/axis_gmii_tx_inst/gmii_txd_next
add wave -noupdate -group axis_gmii_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/eth_mac_1g_rgmii_inst/eth_mac_1g_inst/axis_gmii_tx_inst/reset_crc
add wave -noupdate -group axis_gmii_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/eth_mac_1g_rgmii_inst/eth_mac_1g_inst/axis_gmii_tx_inst/update_crc
add wave -noupdate -group axis_gmii_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/eth_mac_1g_rgmii_inst/eth_mac_1g_inst/axis_gmii_tx_inst/s_tdata_reg
add wave -noupdate -group axis_gmii_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/eth_mac_1g_rgmii_inst/eth_mac_1g_inst/axis_gmii_tx_inst/s_tdata_next
add wave -noupdate -group axis_gmii_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/eth_mac_1g_rgmii_inst/eth_mac_1g_inst/axis_gmii_tx_inst/ifg_reg
add wave -noupdate -group axis_gmii_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/eth_mac_1g_rgmii_inst/eth_mac_1g_inst/axis_gmii_tx_inst/ifg_next
add wave -noupdate -group axis_gmii_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/eth_mac_1g_rgmii_inst/eth_mac_1g_inst/axis_gmii_tx_inst/mii_odd_next
add wave -noupdate -group axis_gmii_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/eth_mac_1g_rgmii_inst/eth_mac_1g_inst/axis_gmii_tx_inst/mii_msn_reg
add wave -noupdate -group axis_gmii_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/eth_mac_1g_rgmii_inst/eth_mac_1g_inst/axis_gmii_tx_inst/mii_msn_next
add wave -noupdate -group axis_gmii_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/eth_mac_1g_rgmii_inst/eth_mac_1g_inst/axis_gmii_tx_inst/frame_ptr_reg
add wave -noupdate -group axis_gmii_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/eth_mac_1g_rgmii_inst/eth_mac_1g_inst/axis_gmii_tx_inst/frame_ptr_next
add wave -noupdate -group axis_gmii_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/eth_mac_1g_rgmii_inst/eth_mac_1g_inst/axis_gmii_tx_inst/gmii_txd_reg
add wave -noupdate -group axis_gmii_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/eth_mac_1g_rgmii_inst/eth_mac_1g_inst/axis_gmii_tx_inst/gmii_tx_en_reg
add wave -noupdate -group axis_gmii_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/eth_mac_1g_rgmii_inst/eth_mac_1g_inst/axis_gmii_tx_inst/gmii_tx_en_next
add wave -noupdate -group axis_gmii_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/eth_mac_1g_rgmii_inst/eth_mac_1g_inst/axis_gmii_tx_inst/gmii_tx_er_reg
add wave -noupdate -group axis_gmii_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/eth_mac_1g_rgmii_inst/eth_mac_1g_inst/axis_gmii_tx_inst/gmii_tx_er_next
add wave -noupdate -group axis_gmii_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/eth_mac_1g_rgmii_inst/eth_mac_1g_inst/axis_gmii_tx_inst/s_axis_tready_reg
add wave -noupdate -group axis_gmii_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/eth_mac_1g_rgmii_inst/eth_mac_1g_inst/axis_gmii_tx_inst/s_axis_tready_next
add wave -noupdate -group axis_gmii_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/eth_mac_1g_rgmii_inst/eth_mac_1g_inst/axis_gmii_tx_inst/crc_state
add wave -noupdate -group axis_gmii_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/eth_mac_1g_rgmii_inst/eth_mac_1g_inst/axis_gmii_tx_inst/fcs_next
add wave -noupdate -group axis_gmii_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/eth_mac_1g_rgmii_inst/eth_mac_1g_inst/axis_gmii_tx_inst/crc_next
add wave -noupdate -group rgmii_phy_if_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/eth_mac_1g_rgmii_inst/rgmii_phy_if_inst/clk
add wave -noupdate -group rgmii_phy_if_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/eth_mac_1g_rgmii_inst/rgmii_phy_if_inst/clk90
add wave -noupdate -group rgmii_phy_if_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/eth_mac_1g_rgmii_inst/rgmii_phy_if_inst/rst
add wave -noupdate -group rgmii_phy_if_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/eth_mac_1g_rgmii_inst/rgmii_phy_if_inst/mac_gmii_rx_clk
add wave -noupdate -group rgmii_phy_if_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/eth_mac_1g_rgmii_inst/rgmii_phy_if_inst/mac_gmii_rx_rst
add wave -noupdate -group rgmii_phy_if_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/eth_mac_1g_rgmii_inst/rgmii_phy_if_inst/mac_gmii_rxd
add wave -noupdate -group rgmii_phy_if_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/eth_mac_1g_rgmii_inst/rgmii_phy_if_inst/mac_gmii_rx_dv
add wave -noupdate -group rgmii_phy_if_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/eth_mac_1g_rgmii_inst/rgmii_phy_if_inst/mac_gmii_rx_er
add wave -noupdate -group rgmii_phy_if_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/eth_mac_1g_rgmii_inst/rgmii_phy_if_inst/mac_gmii_tx_clk
add wave -noupdate -group rgmii_phy_if_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/eth_mac_1g_rgmii_inst/rgmii_phy_if_inst/mac_gmii_tx_rst
add wave -noupdate -group rgmii_phy_if_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/eth_mac_1g_rgmii_inst/rgmii_phy_if_inst/mac_gmii_tx_clk_en
add wave -noupdate -group rgmii_phy_if_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/eth_mac_1g_rgmii_inst/rgmii_phy_if_inst/mac_gmii_txd
add wave -noupdate -group rgmii_phy_if_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/eth_mac_1g_rgmii_inst/rgmii_phy_if_inst/mac_gmii_tx_en
add wave -noupdate -group rgmii_phy_if_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/eth_mac_1g_rgmii_inst/rgmii_phy_if_inst/mac_gmii_tx_er
add wave -noupdate -group rgmii_phy_if_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/eth_mac_1g_rgmii_inst/rgmii_phy_if_inst/phy_rgmii_rx_clk
add wave -noupdate -group rgmii_phy_if_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/eth_mac_1g_rgmii_inst/rgmii_phy_if_inst/phy_rgmii_rxd
add wave -noupdate -group rgmii_phy_if_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/eth_mac_1g_rgmii_inst/rgmii_phy_if_inst/phy_rgmii_rx_ctl
add wave -noupdate -group rgmii_phy_if_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/eth_mac_1g_rgmii_inst/rgmii_phy_if_inst/phy_rgmii_tx_clk
add wave -noupdate -group rgmii_phy_if_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/eth_mac_1g_rgmii_inst/rgmii_phy_if_inst/phy_rgmii_txd
add wave -noupdate -group rgmii_phy_if_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/eth_mac_1g_rgmii_inst/rgmii_phy_if_inst/phy_rgmii_tx_ctl
add wave -noupdate -group rgmii_phy_if_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/eth_mac_1g_rgmii_inst/rgmii_phy_if_inst/speed
add wave -noupdate -group rgmii_phy_if_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/eth_mac_1g_rgmii_inst/rgmii_phy_if_inst/rgmii_rx_ctl_1
add wave -noupdate -group rgmii_phy_if_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/eth_mac_1g_rgmii_inst/rgmii_phy_if_inst/rgmii_rx_ctl_2
add wave -noupdate -group rgmii_phy_if_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/eth_mac_1g_rgmii_inst/rgmii_phy_if_inst/rgmii_tx_clk_1
add wave -noupdate -group rgmii_phy_if_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/eth_mac_1g_rgmii_inst/rgmii_phy_if_inst/rgmii_tx_clk_2
add wave -noupdate -group rgmii_phy_if_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/eth_mac_1g_rgmii_inst/rgmii_phy_if_inst/rgmii_tx_clk_rise
add wave -noupdate -group rgmii_phy_if_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/eth_mac_1g_rgmii_inst/rgmii_phy_if_inst/rgmii_tx_clk_fall
add wave -noupdate -group rgmii_phy_if_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/eth_mac_1g_rgmii_inst/rgmii_phy_if_inst/count_reg
add wave -noupdate -group rgmii_phy_if_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/eth_mac_1g_rgmii_inst/rgmii_phy_if_inst/count_next
add wave -noupdate -group rgmii_phy_if_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/eth_mac_1g_rgmii_inst/rgmii_phy_if_inst/rgmii_txd_1
add wave -noupdate -group rgmii_phy_if_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/eth_mac_1g_rgmii_inst/rgmii_phy_if_inst/rgmii_txd_2
add wave -noupdate -group rgmii_phy_if_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/eth_mac_1g_rgmii_inst/rgmii_phy_if_inst/rgmii_tx_ctl_1
add wave -noupdate -group rgmii_phy_if_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/eth_mac_1g_rgmii_inst/rgmii_phy_if_inst/rgmii_tx_ctl_2
add wave -noupdate -group rgmii_phy_if_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/eth_mac_1g_rgmii_inst/rgmii_phy_if_inst/gmii_clk_en
add wave -noupdate -group rgmii_phy_if_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/eth_mac_1g_rgmii_inst/rgmii_phy_if_inst/phy_rgmii_tx_clk_new
add wave -noupdate -group rgmii_phy_if_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/eth_mac_1g_rgmii_inst/rgmii_phy_if_inst/phy_rgmii_txd_new
add wave -noupdate -group rgmii_phy_if_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/eth_mac_1g_rgmii_inst/rgmii_phy_if_inst/phy_rgmii_tx_ctl_new
add wave -noupdate -group rgmii_phy_if_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/eth_mac_1g_rgmii_inst/rgmii_phy_if_inst/tx_rst_reg
add wave -noupdate -group rgmii_phy_if_tx /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/eth_mac_1g_rgmii_inst/rgmii_phy_if_inst/rx_rst_reg
add wave -noupdate -group tx_fifo /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/tx_fifo/async_rst
add wave -noupdate -group tx_fifo /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/tx_fifo/s_clk
add wave -noupdate -group tx_fifo /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/tx_fifo/s_axis_tdata
add wave -noupdate -group tx_fifo /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/tx_fifo/s_axis_tkeep
add wave -noupdate -group tx_fifo /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/tx_fifo/s_axis_tvalid
add wave -noupdate -group tx_fifo /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/tx_fifo/s_axis_tready
add wave -noupdate -group tx_fifo /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/tx_fifo/s_axis_tlast
add wave -noupdate -group tx_fifo /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/tx_fifo/s_axis_tid
add wave -noupdate -group tx_fifo /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/tx_fifo/s_axis_tdest
add wave -noupdate -group tx_fifo /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/tx_fifo/s_axis_tuser
add wave -noupdate -group tx_fifo /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/tx_fifo/m_clk
add wave -noupdate -group tx_fifo /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/tx_fifo/m_axis_tdata
add wave -noupdate -group tx_fifo /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/tx_fifo/m_axis_tkeep
add wave -noupdate -group tx_fifo /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/tx_fifo/m_axis_tvalid
add wave -noupdate -group tx_fifo /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/tx_fifo/m_axis_tready
add wave -noupdate -group tx_fifo /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/tx_fifo/m_axis_tlast
add wave -noupdate -group tx_fifo /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/tx_fifo/m_axis_tid
add wave -noupdate -group tx_fifo /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/tx_fifo/m_axis_tdest
add wave -noupdate -group tx_fifo /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/tx_fifo/m_axis_tuser
add wave -noupdate -group tx_fifo /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/tx_fifo/s_status_overflow
add wave -noupdate -group tx_fifo /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/tx_fifo/s_status_bad_frame
add wave -noupdate -group tx_fifo /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/tx_fifo/s_status_good_frame
add wave -noupdate -group tx_fifo /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/tx_fifo/m_status_overflow
add wave -noupdate -group tx_fifo /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/tx_fifo/m_status_bad_frame
add wave -noupdate -group tx_fifo /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/tx_fifo/m_status_good_frame
add wave -noupdate -group tx_fifo /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/tx_fifo/wr_ptr_reg
add wave -noupdate -group tx_fifo /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/tx_fifo/wr_ptr_next
add wave -noupdate -group tx_fifo /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/tx_fifo/wr_ptr_cur_reg
add wave -noupdate -group tx_fifo /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/tx_fifo/wr_ptr_cur_next
add wave -noupdate -group tx_fifo /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/tx_fifo/wr_ptr_gray_reg
add wave -noupdate -group tx_fifo /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/tx_fifo/wr_ptr_gray_next
add wave -noupdate -group tx_fifo /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/tx_fifo/wr_ptr_cur_gray_reg
add wave -noupdate -group tx_fifo /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/tx_fifo/wr_ptr_cur_gray_next
add wave -noupdate -group tx_fifo /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/tx_fifo/wr_addr_reg
add wave -noupdate -group tx_fifo /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/tx_fifo/rd_ptr_reg
add wave -noupdate -group tx_fifo /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/tx_fifo/rd_ptr_next
add wave -noupdate -group tx_fifo /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/tx_fifo/rd_ptr_gray_next
add wave -noupdate -group tx_fifo /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/tx_fifo/rd_addr_reg
add wave -noupdate -group tx_fifo /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/tx_fifo/wr_ptr_gray_sync1_reg
add wave -noupdate -group tx_fifo /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/tx_fifo/rd_ptr_gray_sync1_reg
add wave -noupdate -group tx_fifo /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/tx_fifo/rd_ptr_gray_sync2_reg
add wave -noupdate -group tx_fifo /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/tx_fifo/s_rst_sync1_reg
add wave -noupdate -group tx_fifo /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/tx_fifo/s_rst_sync2_reg
add wave -noupdate -group tx_fifo /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/tx_fifo/s_rst_sync3_reg
add wave -noupdate -group tx_fifo /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/tx_fifo/m_rst_sync1_reg
add wave -noupdate -group tx_fifo /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/tx_fifo/m_rst_sync2_reg
add wave -noupdate -group tx_fifo /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/tx_fifo/m_rst_sync3_reg
add wave -noupdate -group tx_fifo /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/tx_fifo/mem_read_data_reg
add wave -noupdate -group tx_fifo /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/tx_fifo/mem_read_data_valid_reg
add wave -noupdate -group tx_fifo /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/tx_fifo/mem_read_data_valid_next
add wave -noupdate -group tx_fifo /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/tx_fifo/s_axis
add wave -noupdate -group tx_fifo /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/tx_fifo/m_axis_reg
add wave -noupdate -group tx_fifo /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/tx_fifo/m_axis_tvalid_reg
add wave -noupdate -group tx_fifo /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/tx_fifo/m_axis_tvalid_next
add wave -noupdate -group tx_fifo /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/tx_fifo/full
add wave -noupdate -group tx_fifo /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/tx_fifo/full_cur
add wave -noupdate -group tx_fifo /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/tx_fifo/empty
add wave -noupdate -group tx_fifo /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/tx_fifo/wr_ptr_gray_sync2_reg
add wave -noupdate -group tx_fifo /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/tx_fifo/rd_ptr_gray_reg
add wave -noupdate -group tx_fifo /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/tx_fifo/full_wr
add wave -noupdate -group tx_fifo /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/tx_fifo/write
add wave -noupdate -group tx_fifo /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/tx_fifo/read
add wave -noupdate -group tx_fifo /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/tx_fifo/store_output
add wave -noupdate -group tx_fifo /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/tx_fifo/drop_frame_reg
add wave -noupdate -group tx_fifo /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/tx_fifo/drop_frame_next
add wave -noupdate -group tx_fifo /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/tx_fifo/overflow_reg
add wave -noupdate -group tx_fifo /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/tx_fifo/overflow_next
add wave -noupdate -group tx_fifo /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/tx_fifo/bad_frame_reg
add wave -noupdate -group tx_fifo /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/tx_fifo/bad_frame_next
add wave -noupdate -group tx_fifo /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/tx_fifo/good_frame_reg
add wave -noupdate -group tx_fifo /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/tx_fifo/good_frame_next
add wave -noupdate -group tx_fifo /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/tx_fifo/overflow_sync1_reg
add wave -noupdate -group tx_fifo /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/tx_fifo/overflow_sync2_reg
add wave -noupdate -group tx_fifo /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/tx_fifo/overflow_sync3_reg
add wave -noupdate -group tx_fifo /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/tx_fifo/overflow_sync4_reg
add wave -noupdate -group tx_fifo /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/tx_fifo/bad_frame_sync1_reg
add wave -noupdate -group tx_fifo /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/tx_fifo/bad_frame_sync2_reg
add wave -noupdate -group tx_fifo /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/tx_fifo/bad_frame_sync3_reg
add wave -noupdate -group tx_fifo /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/tx_fifo/bad_frame_sync4_reg
add wave -noupdate -group tx_fifo /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/tx_fifo/good_frame_sync1_reg
add wave -noupdate -group tx_fifo /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/tx_fifo/good_frame_sync2_reg
add wave -noupdate -group tx_fifo /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/tx_fifo/good_frame_sync3_reg
add wave -noupdate -group tx_fifo /eth_tb/i_eth_rgmii_tx/eth_rgmii/rgmii_soc1/core_inst/eth_mac_inst/tx_fifo/good_frame_sync4_reg
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {4052 ns} 0}
quietly wave cursor active 1
configure wave -namecolwidth 198
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ns} {73454 ns}
